version: 2.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

before_build:
  - nuget restore
  
build:
  project: PdfSharpMigraDocVs2012.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: PDFsharp\code\PdfSharp\bin\Debug\PdfSharp.dll
  - path: PDFsharp\code\PdfSharp\bin\Debug\PdfSharp.pdb
  - path: PDFsharp\code\PdfSharp\bin\Debug\PdfSharp.xml
  - path: PDFsharp\code\PdfSharp.Charting\bin\Debug\PdfSharp.Charting.dll
  - path: PDFsharp\code\PdfSharp.Charting\bin\Debug\PdfSharp.Charting.pdb
  - path: PDFsharp\code\PdfSharp.Charting\bin\Debug\PdfSharp.Charting.xml
  - path: PDFsharp\code\PdfSharp.Xps\bin\Debug\PdfSharp.Xps.dll
  - path: PDFsharp\code\PdfSharp.Xps\bin\Debug\PdfSharp.Xps.pdb
  - path: '**\DotNetProjects.PdfSharp*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: bdhemLvYgto+o1hjkJ9OhVRANxW6+U9RTGQre/KqyV3mFWmN5BQA6ZpMoHbjsaJW
  artifact: /.*\.nupkg/
  
  
  