version: 3.0.{build}

image: Visual Studio 2019

branches:
  only:
    - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Debug

before_build:
  - nuget restore
  
build:
  project: PdfSharpMigraDocVs2012.sln

test: off

artifacts:
  - path: '**\DotNetProjects.PdfSharp*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: bdhemLvYgto+o1hjkJ9OhVRANxW6+U9RTGQre/KqyV3mFWmN5BQA6ZpMoHbjsaJW
  artifact: /.*\.nupkg/
  
  
  